# Generated by Django 2.2.28 on 2023-04-13 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('bid_premium_low', models.FloatField()),
                ('bid_premium_high', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_company', to='company.Company')),
                ('metal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_metal_type', to='portfolio.MetalType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
