# Generated by Django 2.2.28 on 2023-04-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_offer_offerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlist',
            name='user',
        ),
        migrations.AddField(
            model_name='offerlist',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerlist_offer', to='portfolio.Offer'),
        ),
    ]
