# Generated by Django 2.2.28 on 2023-04-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20230413_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlist',
            name='coin',
        ),
    ]
