# Generated by Django 2.2.28 on 2023-04-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0005_remove_offerlist_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlist',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerlist_coin', to='portfolio.Coin'),
        ),
        migrations.AddField(
            model_name='offerlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
