# Generated by Django 2.2.28 on 2023-04-13 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0007_remove_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_offerer', to=settings.AUTH_USER_MODEL),
        ),
    ]
