# Generated by Django 2.2.28 on 2023-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_offer_offerer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaltype',
            name='data',
        ),
        migrations.AddField(
            model_name='metaltype',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='metaltype',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='metaltype',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
