# Generated by Django 2.2.28 on 2023-06-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20230414_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=256),
        ),
    ]
