# Generated by Django 2.2.28 on 2023-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20230613_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlist',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
