# Generated by Django 2.2.28 on 2023-06-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_offerlist_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='quantity',
            new_name='coin_quantity',
        ),
    ]
