# Generated by Django 2.2.28 on 2023-06-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230612_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
